### ISSUE TITLE
Leverage OIDC clients for Client Details

### ISSUE THREAD

**Issue by tvs** [tvs/uaa#6]
We need to leverage IDM's stored OIDC clients for the contents of our Client Details.

## Tasks
- [x] Create Vmidentity-replacements for the various ClientDetails-related services.
- [ ] Enhance OIDC clients with necessary fields (e.g. client secret).
- [ ] Update the VMDir schema to store new data.
- [ ] Verify compatibility between OIDC service and UAA

## Notes
- Ensure that we do not encrypt the client secret in the same way we do identity source passwords, so that we don't run into issues with character encoding (***avoid  ISO-8859-1***)

## Estimate
Two weeks - February 24
