### ISSUE TITLE
Ensure all Zone configuration comes from IDM

### ISSUE THREAD

**Issue by tvs** [tvs/uaa#7]
All zone configuration should stem from IDM - anything else should either be default values or we need to add to IDM.

## Tasks
- [ ] Figure out the delta between zone configuration elements and what exists in IDM
- [ ] Add the necessary elements to IDM
- [ ] Augment the VMDIR schema

## Estimate
Two weeks (maybe less if there's no issue with the schema) - March 10

**Comment by tvs** [comment]
There are a number of elements for which we do not have any sort of analogous data in IDM. For example in `VmidentityIdentityZoneProvisioning`:

* Client lockout policies
* CORS policies
* Links
* Prompts

Changing priority as it doesn't seem to be impacting integration.
